language: node_js
node_js:
  - '6'
  - '8'
  - '9'
  - '10'

script:
  - npm run-script lint
  - npm run-script test:coverage
  - npm run-script test:dist

after_success:
  - npm run-script coveralls

cache:
  yarn: true
  directories:
    - node_modules
